# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
revision: latest

postgresConfig:
  dbPort: 5432
  replicas: 2

mongoConfig:
  dbPort: 5432
  replicas: 2
