---
apiVersion: v1
kind: Service
metadata:
  name: consignment
  labels:
    app: consignment
spec:
  ports:
  - name: grpc
    port: {{ .Values.config.grpcPort }}
  - name: http
    port: 80
    targetPort: {{ .Values.config.httpPort }}
  selector:
    app: consignment
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: consignment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consignment
  template:
    metadata:
      labels:
        app: consignment
    spec:
        containers:
        - name: consignment-service
          image: bege13mot/consignment-service:latest
          imagePullPolicy: Always
          env:
          - name: GRPC_ADDR
            value: ":{{ .Values.config.grpcPort }}"
          - name: GRPC_HTTP_ADDR
            value: ":{{ .Values.config.httpPort }}"
          - name: VESSEL_ADDR
            value: {{ .Values.config.vesselAddr }}
          - name: USER_ADDR
            value: {{ .Values.config.userAddr }}
          - name: DB_HOST
            value: {{ .Values.config.dbHost }}
          ports:
          - containerPort: {{ .Values.config.grpcPort }}
            name: grpc-port
          - containerPort: {{ .Values.config.httpPort }}
            name: http-port
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.config.httpPort }}
