---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: test.test
    http:
      paths:
      - path: /
        backend:
          serviceName: ui
          servicePort: 80
      - path: /Auth
        backend:
          serviceName: user
          servicePort: 80
      - path: /Consignment
        backend:
          serviceName: consignment
          servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: grafana.test
    http:
      paths:
      - path: /
        backend:
          serviceName: grafana
          servicePort: {{ .Values.grafanaPort }}
  - host: prometheus.test
    http:
      paths:
      - path: /
        backend:
          serviceName: prometheus
          servicePort: {{ .Values.prometheusPort }}
